### ISSUE TITLE
The result of sampling is away from the theoretical

### ISSUE THREAD

**Issue by Pei4579** [NTU-CompHydroMet-Lab/pyBL#12] opened 2024-01-24 07:46 UTC
As the pictures in the file, the result of sampling in each scale has deviated from the theoretical value. (red dot: theoretical, box: sampling result) Here, I used Bochum's data, which has a 5-min resolution and with theta read from the file 5Y_1_Theta.csv.

[Archive.zip](https://github.com/NTU-CompHydroMet-Lab/pyBL/files/14034991/Archive.zip)

**Comment by KilinW** [comment] 2024-01-30 17:17
@Pei4579 I found that it's a problem that when `alpha` in the `BLRPRx_params` is smaller than 1. The smaller it gets. The more deviated the result is from theoretical one.
Still looking for the cause. Not sure if it's wrong code or it's supposed to be that. Probably some codes are wrong.
We know that the mean value of time series is directly calculate from `lambda*timescale*iota*mu_c` so the theoretical value are probably right. I'm going to look at sample process. Or it could maybe because of the algorithm of `IndexSnapshot` object

**Comment by KilinW** [comment] 2024-01-31 18:19
The problem is that when alpha is too low. The eta could be very low. (Note that eta is sampled from `gamma(alpha, 1/nu)`).
Those low eta could thus lead to some extremely large storm duration and cell duration. Currently if we limit the `IndexSnapshot` within the range of time we need (i.e. 10 years or 1000 years) and just get rid of any cell after the end time. 
We can have the `IndexSnapshot` with normal statistics then.
I want to point out that this problem also happened in the original c/c++ code from professor. The way they deal with it is just remove those extremely large duration cells or storms.

From this function `InsertMultipleStorms2TimeSeriesArray() in BLM_Storm.h`.
If we go into the function we can then see this line.
```python
if ((idx_sDT < 0) || (idx_sDT >= TS.size()) || idx_eDT >= TS.size()) {
	return;
}
```
We can see that any cell that have invalid start time (<0) or if the start or end time exceed the range.
It was automatically ignored.

Even though it is probably the right solution.
I think we still need to discuss a little bit more before I just directly trim cells that exceed the time range.

**Comment by KilinW** [comment] 2024-02-01 19:23
@Pei4579 The problem had been solved. Please check the [dev1 branch](https://github.com/NTU-CompHydroMet-Lab/pyBL/tree/dev1)

*Change had been merged to main.

**Closed as completed by KilinW** 2024-02-01 19:23 UTC
