### ISSUE TITLE
The inconsistency in the 1 hour mean rainfall  between the statistical and theoretical result 

### ISSUE THREAD

**Issue by chienyutseng** [NTU-CompHydroMet-Lab/pyBL#17] opened 2024-03-13 17:00 UTC
The boxplot of sampling generated from the bootstrap process is consistent with the theoretical analysis results to some extent, but not a perfect match.

However, the biggest issue as mentioned in the title is the inconsistency between the statistical results and the theoretical expected values.

[examples_cy.zip](https://github.com/NTU-CompHydroMet-Lab/pyBL/files/14591043/examples_cy.zip)

**Comment by KilinW** [comment] 2024-03-21 19:11
This issue has been looked. It is not a bug but more like an intended behavior.
Please check the reproduction that I made in the attachment.
In short, it's all because of the low alpha value. And those kind of alphas shouldn't appear during a really successful fitting.
I will not close this issue now since we need more discussion on this.
Because it seems like that alpha can be negative in the paper by professor in 2020?

[reproduce.zip](https://github.com/NTU-CompHydroMet-Lab/pyBL/files/14705865/reproduce.zip)

**Comment by KilinW** [comment] 2024-05-21 09:20
I've confirmed that there is no problem in fitting. It's simply because of the wrong code while setting up target, weight and mask.

[reproduce_17.zip](https://github.com/NTU-CompHydroMet-Lab/pyBL/files/15387618/reproduce_17.zip)

**Closed as completed by KilinW** 2024-05-21 09:20 UTC
